package com.cn.ssm.dao;

public class SysActive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_id
     *
     * @mbggenerated
     */
    private Integer activeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_name
     *
     * @mbggenerated
     */
    private String activeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_context
     *
     * @mbggenerated
     */
    private String activeContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_companyId
     *
     * @mbggenerated
     */
    private String activeCompanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_url
     *
     * @mbggenerated
     */
    private String activeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_uuid
     *
     * @mbggenerated
     */
    private String activeUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_place
     *
     * @mbggenerated
     */
    private String activePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_begintime
     *
     * @mbggenerated
     */
    private String activeBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_active.active_endtime
     *
     * @mbggenerated
     */
    private String activeEndtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_id
     *
     * @return the value of sys_active.active_id
     *
     * @mbggenerated
     */
    public Integer getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_id
     *
     * @param activeId the value for sys_active.active_id
     *
     * @mbggenerated
     */
    public void setActiveId(Integer activeId) {
        this.activeId = activeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_name
     *
     * @return the value of sys_active.active_name
     *
     * @mbggenerated
     */
    public String getActiveName() {
        return activeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_name
     *
     * @param activeName the value for sys_active.active_name
     *
     * @mbggenerated
     */
    public void setActiveName(String activeName) {
        this.activeName = activeName == null ? null : activeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_context
     *
     * @return the value of sys_active.active_context
     *
     * @mbggenerated
     */
    public String getActiveContext() {
        return activeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_context
     *
     * @param activeContext the value for sys_active.active_context
     *
     * @mbggenerated
     */
    public void setActiveContext(String activeContext) {
        this.activeContext = activeContext == null ? null : activeContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_companyId
     *
     * @return the value of sys_active.active_companyId
     *
     * @mbggenerated
     */
    public String getActiveCompanyid() {
        return activeCompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_companyId
     *
     * @param activeCompanyid the value for sys_active.active_companyId
     *
     * @mbggenerated
     */
    public void setActiveCompanyid(String activeCompanyid) {
        this.activeCompanyid = activeCompanyid == null ? null : activeCompanyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_url
     *
     * @return the value of sys_active.active_url
     *
     * @mbggenerated
     */
    public String getActiveUrl() {
        return activeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_url
     *
     * @param activeUrl the value for sys_active.active_url
     *
     * @mbggenerated
     */
    public void setActiveUrl(String activeUrl) {
        this.activeUrl = activeUrl == null ? null : activeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_uuid
     *
     * @return the value of sys_active.active_uuid
     *
     * @mbggenerated
     */
    public String getActiveUuid() {
        return activeUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_uuid
     *
     * @param activeUuid the value for sys_active.active_uuid
     *
     * @mbggenerated
     */
    public void setActiveUuid(String activeUuid) {
        this.activeUuid = activeUuid == null ? null : activeUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_place
     *
     * @return the value of sys_active.active_place
     *
     * @mbggenerated
     */
    public String getActivePlace() {
        return activePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_place
     *
     * @param activePlace the value for sys_active.active_place
     *
     * @mbggenerated
     */
    public void setActivePlace(String activePlace) {
        this.activePlace = activePlace == null ? null : activePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_begintime
     *
     * @return the value of sys_active.active_begintime
     *
     * @mbggenerated
     */
    public String getActiveBegintime() {
        return activeBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_begintime
     *
     * @param activeBegintime the value for sys_active.active_begintime
     *
     * @mbggenerated
     */
    public void setActiveBegintime(String activeBegintime) {
        this.activeBegintime = activeBegintime == null ? null : activeBegintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_active.active_endtime
     *
     * @return the value of sys_active.active_endtime
     *
     * @mbggenerated
     */
    public String getActiveEndtime() {
        return activeEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_active.active_endtime
     *
     * @param activeEndtime the value for sys_active.active_endtime
     *
     * @mbggenerated
     */
    public void setActiveEndtime(String activeEndtime) {
        this.activeEndtime = activeEndtime == null ? null : activeEndtime.trim();
    }
}