package com.cn.ssm.dao;

import java.util.ArrayList;
import java.util.List;

public class SysCompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public SysCompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceIsNull() {
            addCriterion("company_place is null");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceIsNotNull() {
            addCriterion("company_place is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceEqualTo(String value) {
            addCriterion("company_place =", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceNotEqualTo(String value) {
            addCriterion("company_place <>", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceGreaterThan(String value) {
            addCriterion("company_place >", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("company_place >=", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceLessThan(String value) {
            addCriterion("company_place <", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceLessThanOrEqualTo(String value) {
            addCriterion("company_place <=", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceLike(String value) {
            addCriterion("company_place like", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceNotLike(String value) {
            addCriterion("company_place not like", value, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceIn(List<String> values) {
            addCriterion("company_place in", values, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceNotIn(List<String> values) {
            addCriterion("company_place not in", values, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceBetween(String value1, String value2) {
            addCriterion("company_place between", value1, value2, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyPlaceNotBetween(String value1, String value2) {
            addCriterion("company_place not between", value1, value2, "companyPlace");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeIsNull() {
            addCriterion("company_createtime is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeIsNotNull() {
            addCriterion("company_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeEqualTo(String value) {
            addCriterion("company_createtime =", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeNotEqualTo(String value) {
            addCriterion("company_createtime <>", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeGreaterThan(String value) {
            addCriterion("company_createtime >", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("company_createtime >=", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeLessThan(String value) {
            addCriterion("company_createtime <", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("company_createtime <=", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeLike(String value) {
            addCriterion("company_createtime like", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeNotLike(String value) {
            addCriterion("company_createtime not like", value, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeIn(List<String> values) {
            addCriterion("company_createtime in", values, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeNotIn(List<String> values) {
            addCriterion("company_createtime not in", values, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeBetween(String value1, String value2) {
            addCriterion("company_createtime between", value1, value2, "companyCreatetime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreatetimeNotBetween(String value1, String value2) {
            addCriterion("company_createtime not between", value1, value2, "companyCreatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_company
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}