package com.cn.ssm.dao;

public class SysGift {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gift.gift_id
     *
     * @mbggenerated
     */
    private Integer giftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gift.gift_name
     *
     * @mbggenerated
     */
    private String giftName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gift.gift_price
     *
     * @mbggenerated
     */
    private Integer giftPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gift.gift_ticket
     *
     * @mbggenerated
     */
    private Integer giftTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_gift.gift_img
     *
     * @mbggenerated
     */
    private String giftImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gift.gift_id
     *
     * @return the value of sys_gift.gift_id
     *
     * @mbggenerated
     */
    public Integer getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gift.gift_id
     *
     * @param giftId the value for sys_gift.gift_id
     *
     * @mbggenerated
     */
    public void setGiftId(Integer giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gift.gift_name
     *
     * @return the value of sys_gift.gift_name
     *
     * @mbggenerated
     */
    public String getGiftName() {
        return giftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gift.gift_name
     *
     * @param giftName the value for sys_gift.gift_name
     *
     * @mbggenerated
     */
    public void setGiftName(String giftName) {
        this.giftName = giftName == null ? null : giftName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gift.gift_price
     *
     * @return the value of sys_gift.gift_price
     *
     * @mbggenerated
     */
    public Integer getGiftPrice() {
        return giftPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gift.gift_price
     *
     * @param giftPrice the value for sys_gift.gift_price
     *
     * @mbggenerated
     */
    public void setGiftPrice(Integer giftPrice) {
        this.giftPrice = giftPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gift.gift_ticket
     *
     * @return the value of sys_gift.gift_ticket
     *
     * @mbggenerated
     */
    public Integer getGiftTicket() {
        return giftTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gift.gift_ticket
     *
     * @param giftTicket the value for sys_gift.gift_ticket
     *
     * @mbggenerated
     */
    public void setGiftTicket(Integer giftTicket) {
        this.giftTicket = giftTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_gift.gift_img
     *
     * @return the value of sys_gift.gift_img
     *
     * @mbggenerated
     */
    public String getGiftImg() {
        return giftImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_gift.gift_img
     *
     * @param giftImg the value for sys_gift.gift_img
     *
     * @mbggenerated
     */
    public void setGiftImg(String giftImg) {
        this.giftImg = giftImg == null ? null : giftImg.trim();
    }
}