package com.cn.ssm.dao;

import java.util.ArrayList;
import java.util.List;

public class SysPrizeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public SysPrizeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrizeIdIsNull() {
            addCriterion("prize_id is null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIsNotNull() {
            addCriterion("prize_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdEqualTo(Integer value) {
            addCriterion("prize_id =", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotEqualTo(Integer value) {
            addCriterion("prize_id <>", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThan(Integer value) {
            addCriterion("prize_id >", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_id >=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThan(Integer value) {
            addCriterion("prize_id <", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThanOrEqualTo(Integer value) {
            addCriterion("prize_id <=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIn(List<Integer> values) {
            addCriterion("prize_id in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotIn(List<Integer> values) {
            addCriterion("prize_id not in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdBetween(Integer value1, Integer value2) {
            addCriterion("prize_id between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_id not between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIsNull() {
            addCriterion("prize_name is null");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIsNotNull() {
            addCriterion("prize_name is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeNameEqualTo(String value) {
            addCriterion("prize_name =", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotEqualTo(String value) {
            addCriterion("prize_name <>", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameGreaterThan(String value) {
            addCriterion("prize_name >", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameGreaterThanOrEqualTo(String value) {
            addCriterion("prize_name >=", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLessThan(String value) {
            addCriterion("prize_name <", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLessThanOrEqualTo(String value) {
            addCriterion("prize_name <=", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLike(String value) {
            addCriterion("prize_name like", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotLike(String value) {
            addCriterion("prize_name not like", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIn(List<String> values) {
            addCriterion("prize_name in", values, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotIn(List<String> values) {
            addCriterion("prize_name not in", values, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameBetween(String value1, String value2) {
            addCriterion("prize_name between", value1, value2, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotBetween(String value1, String value2) {
            addCriterion("prize_name not between", value1, value2, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeContextIsNull() {
            addCriterion("prize_context is null");
            return (Criteria) this;
        }

        public Criteria andPrizeContextIsNotNull() {
            addCriterion("prize_context is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeContextEqualTo(String value) {
            addCriterion("prize_context =", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextNotEqualTo(String value) {
            addCriterion("prize_context <>", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextGreaterThan(String value) {
            addCriterion("prize_context >", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextGreaterThanOrEqualTo(String value) {
            addCriterion("prize_context >=", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextLessThan(String value) {
            addCriterion("prize_context <", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextLessThanOrEqualTo(String value) {
            addCriterion("prize_context <=", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextLike(String value) {
            addCriterion("prize_context like", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextNotLike(String value) {
            addCriterion("prize_context not like", value, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextIn(List<String> values) {
            addCriterion("prize_context in", values, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextNotIn(List<String> values) {
            addCriterion("prize_context not in", values, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextBetween(String value1, String value2) {
            addCriterion("prize_context between", value1, value2, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeContextNotBetween(String value1, String value2) {
            addCriterion("prize_context not between", value1, value2, "prizeContext");
            return (Criteria) this;
        }

        public Criteria andPrizeImgIsNull() {
            addCriterion("prize_img is null");
            return (Criteria) this;
        }

        public Criteria andPrizeImgIsNotNull() {
            addCriterion("prize_img is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeImgEqualTo(String value) {
            addCriterion("prize_img =", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgNotEqualTo(String value) {
            addCriterion("prize_img <>", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgGreaterThan(String value) {
            addCriterion("prize_img >", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgGreaterThanOrEqualTo(String value) {
            addCriterion("prize_img >=", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgLessThan(String value) {
            addCriterion("prize_img <", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgLessThanOrEqualTo(String value) {
            addCriterion("prize_img <=", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgLike(String value) {
            addCriterion("prize_img like", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgNotLike(String value) {
            addCriterion("prize_img not like", value, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgIn(List<String> values) {
            addCriterion("prize_img in", values, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgNotIn(List<String> values) {
            addCriterion("prize_img not in", values, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgBetween(String value1, String value2) {
            addCriterion("prize_img between", value1, value2, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeImgNotBetween(String value1, String value2) {
            addCriterion("prize_img not between", value1, value2, "prizeImg");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidIsNull() {
            addCriterion("prize_parentId is null");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidIsNotNull() {
            addCriterion("prize_parentId is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidEqualTo(Integer value) {
            addCriterion("prize_parentId =", value, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidNotEqualTo(Integer value) {
            addCriterion("prize_parentId <>", value, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidGreaterThan(Integer value) {
            addCriterion("prize_parentId >", value, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_parentId >=", value, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidLessThan(Integer value) {
            addCriterion("prize_parentId <", value, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidLessThanOrEqualTo(Integer value) {
            addCriterion("prize_parentId <=", value, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidIn(List<Integer> values) {
            addCriterion("prize_parentId in", values, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidNotIn(List<Integer> values) {
            addCriterion("prize_parentId not in", values, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidBetween(Integer value1, Integer value2) {
            addCriterion("prize_parentId between", value1, value2, "prizeParentid");
            return (Criteria) this;
        }

        public Criteria andPrizeParentidNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_parentId not between", value1, value2, "prizeParentid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_prize
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_prize
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}