package com.cn.ssm.dao;

public class SysStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_img
     *
     * @mbggenerated
     */
    private String studentImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_age
     *
     * @mbggenerated
     */
    private String studentAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_context
     *
     * @mbggenerated
     */
    private String studentContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_code
     *
     * @mbggenerated
     */
    private String studentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_ticket
     *
     * @mbggenerated
     */
    private Integer studentTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_activeId
     *
     * @mbggenerated
     */
    private String studentActiveid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_student.student_numb
     *
     * @mbggenerated
     */
    private String studentNumb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_id
     *
     * @return the value of sys_student.student_id
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_id
     *
     * @param studentId the value for sys_student.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_name
     *
     * @return the value of sys_student.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_name
     *
     * @param studentName the value for sys_student.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_img
     *
     * @return the value of sys_student.student_img
     *
     * @mbggenerated
     */
    public String getStudentImg() {
        return studentImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_img
     *
     * @param studentImg the value for sys_student.student_img
     *
     * @mbggenerated
     */
    public void setStudentImg(String studentImg) {
        this.studentImg = studentImg == null ? null : studentImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_age
     *
     * @return the value of sys_student.student_age
     *
     * @mbggenerated
     */
    public String getStudentAge() {
        return studentAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_age
     *
     * @param studentAge the value for sys_student.student_age
     *
     * @mbggenerated
     */
    public void setStudentAge(String studentAge) {
        this.studentAge = studentAge == null ? null : studentAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_context
     *
     * @return the value of sys_student.student_context
     *
     * @mbggenerated
     */
    public String getStudentContext() {
        return studentContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_context
     *
     * @param studentContext the value for sys_student.student_context
     *
     * @mbggenerated
     */
    public void setStudentContext(String studentContext) {
        this.studentContext = studentContext == null ? null : studentContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_code
     *
     * @return the value of sys_student.student_code
     *
     * @mbggenerated
     */
    public String getStudentCode() {
        return studentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_code
     *
     * @param studentCode the value for sys_student.student_code
     *
     * @mbggenerated
     */
    public void setStudentCode(String studentCode) {
        this.studentCode = studentCode == null ? null : studentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_ticket
     *
     * @return the value of sys_student.student_ticket
     *
     * @mbggenerated
     */
    public Integer getStudentTicket() {
        return studentTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_ticket
     *
     * @param studentTicket the value for sys_student.student_ticket
     *
     * @mbggenerated
     */
    public void setStudentTicket(Integer studentTicket) {
        this.studentTicket = studentTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_activeId
     *
     * @return the value of sys_student.student_activeId
     *
     * @mbggenerated
     */
    public String getStudentActiveid() {
        return studentActiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_activeId
     *
     * @param studentActiveid the value for sys_student.student_activeId
     *
     * @mbggenerated
     */
    public void setStudentActiveid(String studentActiveid) {
        this.studentActiveid = studentActiveid == null ? null : studentActiveid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_student.student_numb
     *
     * @return the value of sys_student.student_numb
     *
     * @mbggenerated
     */
    public String getStudentNumb() {
        return studentNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_student.student_numb
     *
     * @param studentNumb the value for sys_student.student_numb
     *
     * @mbggenerated
     */
    public void setStudentNumb(String studentNumb) {
        this.studentNumb = studentNumb == null ? null : studentNumb.trim();
    }
}