package com.cn.ssm.dao;

import java.util.ArrayList;
import java.util.List;

public class SysStudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public SysStudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudentNameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNameEqualTo(String value) {
            addCriterion("student_name =", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThan(String value) {
            addCriterion("student_name >", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThan(String value) {
            addCriterion("student_name <", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameLike(String value) {
            addCriterion("student_name like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotLike(String value) {
            addCriterion("student_name not like", value, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameIn(List<String> values) {
            addCriterion("student_name in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentNameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "studentName");
            return (Criteria) this;
        }

        public Criteria andStudentImgIsNull() {
            addCriterion("student_img is null");
            return (Criteria) this;
        }

        public Criteria andStudentImgIsNotNull() {
            addCriterion("student_img is not null");
            return (Criteria) this;
        }

        public Criteria andStudentImgEqualTo(String value) {
            addCriterion("student_img =", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgNotEqualTo(String value) {
            addCriterion("student_img <>", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgGreaterThan(String value) {
            addCriterion("student_img >", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgGreaterThanOrEqualTo(String value) {
            addCriterion("student_img >=", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgLessThan(String value) {
            addCriterion("student_img <", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgLessThanOrEqualTo(String value) {
            addCriterion("student_img <=", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgLike(String value) {
            addCriterion("student_img like", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgNotLike(String value) {
            addCriterion("student_img not like", value, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgIn(List<String> values) {
            addCriterion("student_img in", values, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgNotIn(List<String> values) {
            addCriterion("student_img not in", values, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgBetween(String value1, String value2) {
            addCriterion("student_img between", value1, value2, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentImgNotBetween(String value1, String value2) {
            addCriterion("student_img not between", value1, value2, "studentImg");
            return (Criteria) this;
        }

        public Criteria andStudentAgeIsNull() {
            addCriterion("student_age is null");
            return (Criteria) this;
        }

        public Criteria andStudentAgeIsNotNull() {
            addCriterion("student_age is not null");
            return (Criteria) this;
        }

        public Criteria andStudentAgeEqualTo(String value) {
            addCriterion("student_age =", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeNotEqualTo(String value) {
            addCriterion("student_age <>", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeGreaterThan(String value) {
            addCriterion("student_age >", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeGreaterThanOrEqualTo(String value) {
            addCriterion("student_age >=", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeLessThan(String value) {
            addCriterion("student_age <", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeLessThanOrEqualTo(String value) {
            addCriterion("student_age <=", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeLike(String value) {
            addCriterion("student_age like", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeNotLike(String value) {
            addCriterion("student_age not like", value, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeIn(List<String> values) {
            addCriterion("student_age in", values, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeNotIn(List<String> values) {
            addCriterion("student_age not in", values, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeBetween(String value1, String value2) {
            addCriterion("student_age between", value1, value2, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentAgeNotBetween(String value1, String value2) {
            addCriterion("student_age not between", value1, value2, "studentAge");
            return (Criteria) this;
        }

        public Criteria andStudentContextIsNull() {
            addCriterion("student_context is null");
            return (Criteria) this;
        }

        public Criteria andStudentContextIsNotNull() {
            addCriterion("student_context is not null");
            return (Criteria) this;
        }

        public Criteria andStudentContextEqualTo(String value) {
            addCriterion("student_context =", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextNotEqualTo(String value) {
            addCriterion("student_context <>", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextGreaterThan(String value) {
            addCriterion("student_context >", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextGreaterThanOrEqualTo(String value) {
            addCriterion("student_context >=", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextLessThan(String value) {
            addCriterion("student_context <", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextLessThanOrEqualTo(String value) {
            addCriterion("student_context <=", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextLike(String value) {
            addCriterion("student_context like", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextNotLike(String value) {
            addCriterion("student_context not like", value, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextIn(List<String> values) {
            addCriterion("student_context in", values, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextNotIn(List<String> values) {
            addCriterion("student_context not in", values, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextBetween(String value1, String value2) {
            addCriterion("student_context between", value1, value2, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentContextNotBetween(String value1, String value2) {
            addCriterion("student_context not between", value1, value2, "studentContext");
            return (Criteria) this;
        }

        public Criteria andStudentCodeIsNull() {
            addCriterion("student_code is null");
            return (Criteria) this;
        }

        public Criteria andStudentCodeIsNotNull() {
            addCriterion("student_code is not null");
            return (Criteria) this;
        }

        public Criteria andStudentCodeEqualTo(String value) {
            addCriterion("student_code =", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeNotEqualTo(String value) {
            addCriterion("student_code <>", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeGreaterThan(String value) {
            addCriterion("student_code >", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("student_code >=", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeLessThan(String value) {
            addCriterion("student_code <", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeLessThanOrEqualTo(String value) {
            addCriterion("student_code <=", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeLike(String value) {
            addCriterion("student_code like", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeNotLike(String value) {
            addCriterion("student_code not like", value, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeIn(List<String> values) {
            addCriterion("student_code in", values, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeNotIn(List<String> values) {
            addCriterion("student_code not in", values, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeBetween(String value1, String value2) {
            addCriterion("student_code between", value1, value2, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentCodeNotBetween(String value1, String value2) {
            addCriterion("student_code not between", value1, value2, "studentCode");
            return (Criteria) this;
        }

        public Criteria andStudentTicketIsNull() {
            addCriterion("student_ticket is null");
            return (Criteria) this;
        }

        public Criteria andStudentTicketIsNotNull() {
            addCriterion("student_ticket is not null");
            return (Criteria) this;
        }

        public Criteria andStudentTicketEqualTo(Integer value) {
            addCriterion("student_ticket =", value, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketNotEqualTo(Integer value) {
            addCriterion("student_ticket <>", value, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketGreaterThan(Integer value) {
            addCriterion("student_ticket >", value, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_ticket >=", value, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketLessThan(Integer value) {
            addCriterion("student_ticket <", value, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketLessThanOrEqualTo(Integer value) {
            addCriterion("student_ticket <=", value, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketIn(List<Integer> values) {
            addCriterion("student_ticket in", values, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketNotIn(List<Integer> values) {
            addCriterion("student_ticket not in", values, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketBetween(Integer value1, Integer value2) {
            addCriterion("student_ticket between", value1, value2, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentTicketNotBetween(Integer value1, Integer value2) {
            addCriterion("student_ticket not between", value1, value2, "studentTicket");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidIsNull() {
            addCriterion("student_activeId is null");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidIsNotNull() {
            addCriterion("student_activeId is not null");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidEqualTo(String value) {
            addCriterion("student_activeId =", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidNotEqualTo(String value) {
            addCriterion("student_activeId <>", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidGreaterThan(String value) {
            addCriterion("student_activeId >", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidGreaterThanOrEqualTo(String value) {
            addCriterion("student_activeId >=", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidLessThan(String value) {
            addCriterion("student_activeId <", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidLessThanOrEqualTo(String value) {
            addCriterion("student_activeId <=", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidLike(String value) {
            addCriterion("student_activeId like", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidNotLike(String value) {
            addCriterion("student_activeId not like", value, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidIn(List<String> values) {
            addCriterion("student_activeId in", values, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidNotIn(List<String> values) {
            addCriterion("student_activeId not in", values, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidBetween(String value1, String value2) {
            addCriterion("student_activeId between", value1, value2, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentActiveidNotBetween(String value1, String value2) {
            addCriterion("student_activeId not between", value1, value2, "studentActiveid");
            return (Criteria) this;
        }

        public Criteria andStudentNumbIsNull() {
            addCriterion("student_numb is null");
            return (Criteria) this;
        }

        public Criteria andStudentNumbIsNotNull() {
            addCriterion("student_numb is not null");
            return (Criteria) this;
        }

        public Criteria andStudentNumbEqualTo(String value) {
            addCriterion("student_numb =", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbNotEqualTo(String value) {
            addCriterion("student_numb <>", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbGreaterThan(String value) {
            addCriterion("student_numb >", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbGreaterThanOrEqualTo(String value) {
            addCriterion("student_numb >=", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbLessThan(String value) {
            addCriterion("student_numb <", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbLessThanOrEqualTo(String value) {
            addCriterion("student_numb <=", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbLike(String value) {
            addCriterion("student_numb like", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbNotLike(String value) {
            addCriterion("student_numb not like", value, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbIn(List<String> values) {
            addCriterion("student_numb in", values, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbNotIn(List<String> values) {
            addCriterion("student_numb not in", values, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbBetween(String value1, String value2) {
            addCriterion("student_numb between", value1, value2, "studentNumb");
            return (Criteria) this;
        }

        public Criteria andStudentNumbNotBetween(String value1, String value2) {
            addCriterion("student_numb not between", value1, value2, "studentNumb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_student
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}