package com.cn.ssm.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysTicketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public SysTicketExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTicketIdIsNull() {
            addCriterion("ticket_id is null");
            return (Criteria) this;
        }

        public Criteria andTicketIdIsNotNull() {
            addCriterion("ticket_id is not null");
            return (Criteria) this;
        }

        public Criteria andTicketIdEqualTo(Integer value) {
            addCriterion("ticket_id =", value, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdNotEqualTo(Integer value) {
            addCriterion("ticket_id <>", value, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdGreaterThan(Integer value) {
            addCriterion("ticket_id >", value, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticket_id >=", value, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdLessThan(Integer value) {
            addCriterion("ticket_id <", value, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdLessThanOrEqualTo(Integer value) {
            addCriterion("ticket_id <=", value, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdIn(List<Integer> values) {
            addCriterion("ticket_id in", values, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdNotIn(List<Integer> values) {
            addCriterion("ticket_id not in", values, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdBetween(Integer value1, Integer value2) {
            addCriterion("ticket_id between", value1, value2, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ticket_id not between", value1, value2, "ticketId");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidIsNull() {
            addCriterion("ticket_openid is null");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidIsNotNull() {
            addCriterion("ticket_openid is not null");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidEqualTo(String value) {
            addCriterion("ticket_openid =", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidNotEqualTo(String value) {
            addCriterion("ticket_openid <>", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidGreaterThan(String value) {
            addCriterion("ticket_openid >", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("ticket_openid >=", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidLessThan(String value) {
            addCriterion("ticket_openid <", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidLessThanOrEqualTo(String value) {
            addCriterion("ticket_openid <=", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidLike(String value) {
            addCriterion("ticket_openid like", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidNotLike(String value) {
            addCriterion("ticket_openid not like", value, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidIn(List<String> values) {
            addCriterion("ticket_openid in", values, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidNotIn(List<String> values) {
            addCriterion("ticket_openid not in", values, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidBetween(String value1, String value2) {
            addCriterion("ticket_openid between", value1, value2, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketOpenidNotBetween(String value1, String value2) {
            addCriterion("ticket_openid not between", value1, value2, "ticketOpenid");
            return (Criteria) this;
        }

        public Criteria andTicketNumbIsNull() {
            addCriterion("ticket_numb is null");
            return (Criteria) this;
        }

        public Criteria andTicketNumbIsNotNull() {
            addCriterion("ticket_numb is not null");
            return (Criteria) this;
        }

        public Criteria andTicketNumbEqualTo(Integer value) {
            addCriterion("ticket_numb =", value, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbNotEqualTo(Integer value) {
            addCriterion("ticket_numb <>", value, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbGreaterThan(Integer value) {
            addCriterion("ticket_numb >", value, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticket_numb >=", value, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbLessThan(Integer value) {
            addCriterion("ticket_numb <", value, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbLessThanOrEqualTo(Integer value) {
            addCriterion("ticket_numb <=", value, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbIn(List<Integer> values) {
            addCriterion("ticket_numb in", values, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbNotIn(List<Integer> values) {
            addCriterion("ticket_numb not in", values, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbBetween(Integer value1, Integer value2) {
            addCriterion("ticket_numb between", value1, value2, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketNumbNotBetween(Integer value1, Integer value2) {
            addCriterion("ticket_numb not between", value1, value2, "ticketNumb");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidIsNull() {
            addCriterion("ticket_studentid is null");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidIsNotNull() {
            addCriterion("ticket_studentid is not null");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidEqualTo(Integer value) {
            addCriterion("ticket_studentid =", value, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidNotEqualTo(Integer value) {
            addCriterion("ticket_studentid <>", value, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidGreaterThan(Integer value) {
            addCriterion("ticket_studentid >", value, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ticket_studentid >=", value, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidLessThan(Integer value) {
            addCriterion("ticket_studentid <", value, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidLessThanOrEqualTo(Integer value) {
            addCriterion("ticket_studentid <=", value, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidIn(List<Integer> values) {
            addCriterion("ticket_studentid in", values, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidNotIn(List<Integer> values) {
            addCriterion("ticket_studentid not in", values, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidBetween(Integer value1, Integer value2) {
            addCriterion("ticket_studentid between", value1, value2, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketStudentidNotBetween(Integer value1, Integer value2) {
            addCriterion("ticket_studentid not between", value1, value2, "ticketStudentid");
            return (Criteria) this;
        }

        public Criteria andTicketTimeIsNull() {
            addCriterion("ticket_time is null");
            return (Criteria) this;
        }

        public Criteria andTicketTimeIsNotNull() {
            addCriterion("ticket_time is not null");
            return (Criteria) this;
        }

        public Criteria andTicketTimeEqualTo(Date value) {
            addCriterion("ticket_time =", value, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeNotEqualTo(Date value) {
            addCriterion("ticket_time <>", value, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeGreaterThan(Date value) {
            addCriterion("ticket_time >", value, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ticket_time >=", value, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeLessThan(Date value) {
            addCriterion("ticket_time <", value, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeLessThanOrEqualTo(Date value) {
            addCriterion("ticket_time <=", value, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeIn(List<Date> values) {
            addCriterion("ticket_time in", values, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeNotIn(List<Date> values) {
            addCriterion("ticket_time not in", values, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeBetween(Date value1, Date value2) {
            addCriterion("ticket_time between", value1, value2, "ticketTime");
            return (Criteria) this;
        }

        public Criteria andTicketTimeNotBetween(Date value1, Date value2) {
            addCriterion("ticket_time not between", value1, value2, "ticketTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_ticket
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_ticket
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}