package com.cn.ssm.dao;

import java.util.Date;

public class SysTicket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ticket.ticket_id
     *
     * @mbg.generated
     */
    private Integer ticketId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ticket.ticket_openid
     *
     * @mbg.generated
     */
    private String ticketOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ticket.ticket_numb
     *
     * @mbg.generated
     */
    private Integer ticketNumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ticket.ticket_studentid
     *
     * @mbg.generated
     */
    private Integer ticketStudentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ticket.ticket_time
     *
     * @mbg.generated
     */
    private Date ticketTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ticket.ticket_id
     *
     * @return the value of sys_ticket.ticket_id
     *
     * @mbg.generated
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ticket.ticket_id
     *
     * @param ticketId the value for sys_ticket.ticket_id
     *
     * @mbg.generated
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ticket.ticket_openid
     *
     * @return the value of sys_ticket.ticket_openid
     *
     * @mbg.generated
     */
    public String getTicketOpenid() {
        return ticketOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ticket.ticket_openid
     *
     * @param ticketOpenid the value for sys_ticket.ticket_openid
     *
     * @mbg.generated
     */
    public void setTicketOpenid(String ticketOpenid) {
        this.ticketOpenid = ticketOpenid == null ? null : ticketOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ticket.ticket_numb
     *
     * @return the value of sys_ticket.ticket_numb
     *
     * @mbg.generated
     */
    public Integer getTicketNumb() {
        return ticketNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ticket.ticket_numb
     *
     * @param ticketNumb the value for sys_ticket.ticket_numb
     *
     * @mbg.generated
     */
    public void setTicketNumb(Integer ticketNumb) {
        this.ticketNumb = ticketNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ticket.ticket_studentid
     *
     * @return the value of sys_ticket.ticket_studentid
     *
     * @mbg.generated
     */
    public Integer getTicketStudentid() {
        return ticketStudentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ticket.ticket_studentid
     *
     * @param ticketStudentid the value for sys_ticket.ticket_studentid
     *
     * @mbg.generated
     */
    public void setTicketStudentid(Integer ticketStudentid) {
        this.ticketStudentid = ticketStudentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ticket.ticket_time
     *
     * @return the value of sys_ticket.ticket_time
     *
     * @mbg.generated
     */
    public Date getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ticket.ticket_time
     *
     * @param ticketTime the value for sys_ticket.ticket_time
     *
     * @mbg.generated
     */
    public void setTicketTime(Date ticketTime) {
        this.ticketTime = ticketTime;
    }
}