package com.cn.ssm.dao;

public class SysWatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_watch.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_watch.watch_numb
     *
     * @mbg.generated
     */
    private Integer watchNumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_watch.watch_activeId
     *
     * @mbg.generated
     */
    private Integer watchActiveid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_watch.id
     *
     * @return the value of sys_watch.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_watch.id
     *
     * @param id the value for sys_watch.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_watch.watch_numb
     *
     * @return the value of sys_watch.watch_numb
     *
     * @mbg.generated
     */
    public Integer getWatchNumb() {
        return watchNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_watch.watch_numb
     *
     * @param watchNumb the value for sys_watch.watch_numb
     *
     * @mbg.generated
     */
    public void setWatchNumb(Integer watchNumb) {
        this.watchNumb = watchNumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_watch.watch_activeId
     *
     * @return the value of sys_watch.watch_activeId
     *
     * @mbg.generated
     */
    public Integer getWatchActiveid() {
        return watchActiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_watch.watch_activeId
     *
     * @param watchActiveid the value for sys_watch.watch_activeId
     *
     * @mbg.generated
     */
    public void setWatchActiveid(Integer watchActiveid) {
        this.watchActiveid = watchActiveid;
    }
}