package com.cn.ssm.mapping;

import com.cn.ssm.dao.SysActive;
import com.cn.ssm.dao.SysActiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysActiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int countByExample(SysActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int deleteByExample(SysActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer activeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int insert(SysActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int insertSelective(SysActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    List<SysActive> selectByExample(SysActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    SysActive selectByPrimaryKey(Integer activeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysActive record, @Param("example") SysActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysActive record, @Param("example") SysActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_active
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysActive record);
}