package com.cn.ssm.mapping;

import com.cn.ssm.dao.SysCompany;
import com.cn.ssm.dao.SysCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int countByExample(SysCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int deleteByExample(SysCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int insert(SysCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int insertSelective(SysCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    List<SysCompany> selectByExample(SysCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    SysCompany selectByPrimaryKey(Integer companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysCompany record, @Param("example") SysCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysCompany record, @Param("example") SysCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysCompany record);
}