package com.cn.ssm.mapping;

import com.cn.ssm.dao.SysGift;
import com.cn.ssm.dao.SysGiftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int countByExample(SysGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int deleteByExample(SysGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer giftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int insert(SysGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int insertSelective(SysGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    List<SysGift> selectByExample(SysGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    SysGift selectByPrimaryKey(Integer giftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysGift record, @Param("example") SysGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysGift record, @Param("example") SysGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysGift record);
}