package com.cn.ssm.mapping;

import com.cn.ssm.dao.SysImg;
import com.cn.ssm.dao.SysImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    long countByExample(SysImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int deleteByExample(SysImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int insert(SysImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int insertSelective(SysImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    List<SysImg> selectByExample(SysImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    SysImg selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysImg record, @Param("example") SysImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysImg record, @Param("example") SysImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysImg record);
}