package com.cn.ssm.mapping;

import com.cn.ssm.dao.SysStudent;
import com.cn.ssm.dao.SysStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int countByExample(SysStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int deleteByExample(SysStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int insert(SysStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int insertSelective(SysStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    List<SysStudent> selectByExample(SysStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    SysStudent selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysStudent record, @Param("example") SysStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysStudent record, @Param("example") SysStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysStudent record);
}