package com.cn.ssm.mapping;

import com.cn.ssm.dao.SysWechat;
import com.cn.ssm.dao.SysWechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    long countByExample(SysWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int deleteByExample(SysWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int insert(SysWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int insertSelective(SysWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    List<SysWechat> selectByExample(SysWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    SysWechat selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysWechat record, @Param("example") SysWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysWechat record, @Param("example") SysWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_wechat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysWechat record);
}