package com.cn.ssm.mapping;

import com.cn.ssm.dao.SysWatch;
import com.cn.ssm.dao.SysWatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysWatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    long countByExample(SysWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int deleteByExample(SysWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int insert(SysWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int insertSelective(SysWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    List<SysWatch> selectByExample(SysWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    SysWatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysWatch record, @Param("example") SysWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysWatch record, @Param("example") SysWatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysWatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_watch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysWatch record);
}